/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CompositionChapterNav: typeof import('./src/components/CompositionChapterNav.vue')['default']
    DSChapterNav: typeof import('./src/components/DSChapterNav.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    ExamFrequencyMap: typeof import('./src/components/ExamFrequencyMap.vue')['default']
    FeynmanLearning: typeof import('./src/components/FeynmanLearning.vue')['default']
    KnowledgeCard: typeof import('./src/components/KnowledgeCard.vue')['default']
    KnowledgeStructure: typeof import('./src/components/KnowledgeStructure.vue')['default']
    MathReinforcementNav: typeof import('./src/components/MathReinforcementNav.vue')['default']
    MindMapView: typeof import('./src/components/MindMapView.vue')['default']
    NetworkChapterNav: typeof import('./src/components/NetworkChapterNav.vue')['default']
    OSChapterNav: typeof import('./src/components/OSChapterNav.vue')['default']
    OSMindMapView: typeof import('./src/components/OSMindMapView.vue')['default']
    PoliticsKnowledge: typeof import('./src/components/PoliticsKnowledge.vue')['default']
    PoliticsReciteCards: typeof import('./src/components/PoliticsReciteCards.vue')['default']
    QuickCards: typeof import('./src/components/QuickCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
